### ISSUE TITLE
Stopping and starting a kafka server while producing and consuming causes duplicates

### ISSUE THREAD

**Issue by tteats** [ExactTargetDev/kafka#14]
I have 3 kafka nodes running by 20 partitions. I run the test client:

KafkaTest.exe -p=20 -c=10 --stats-rerun-ms=60000 --producer-sleep-ms=8 --consume-sleep-ms=5 --name=KafkaStop

(you may need an updated exe for this test since it does require some bug fixes there.)

After a minute I stop one of the kafka nodes.  I wait a couple minutes, then turn kafka back on; wait another couple minutes, then quit the test.  After fixing some issues with the TcpConnection from Kafka, I do get 100% of the messages back. However, a substantial amount do end up getting replayed.  I don't know if this is b/c the failure causes the consumer offsets for that node to be stale or what the issue is.

As a side note, if you run the same test, only you never start back up the kafka server, you don't ever consume the messages on the stopped kafka node, which is expected. However, you do get lots of duplicate messages there too.

**Comment by tteats** [comment]
Correction from the original issue. I do not get 100% of the messages consumed. There is a large number of messages that never get consumed too.

**Comment by ppekrol** [comment]
I was researching this issue and I discovered couple of facts that may be interesting:

1) when a producer sends a message it takes some time for kafka to save it on a storage so if you will kill a node some messages may be lost
In our env I started 20 producers and saving 100k messages took few minutes (virtual machines).
So when one of the nodes was killed, the messages that were send to it and did not make it to the storage were lost forever.

This, I think, is the reason that causes you to think that not all messages are processed, which is actually true, but we cant do anything without it.

2) when I was absolutely sure that all messages were saved in the storage, I started 10 consumers and almost immediately killed one of the nodes and started it few seconds later.
The rebalancing took some time (1 minute in our env) but eventually all the messages were consumed. No duplicates.

3) my second attempt was similar to the first one, but after killing the node I never started it back. The consumers finished processing the messages but as you described not all produced messages were processed, which is expected. Then I started the node that I killed and started the consumers again and they processed the missing messages. No duplicates either.

We noticed also that our producer when disposed is not trying to send remaining messages, it just drops them.
We do not know if this is an expected behavior. There is a possibility to add http://msdn.microsoft.com/en-us/library/system.net.sockets.lingeroption.aspx
What is your opinion?

**Comment by ewhauser** [comment]
1) I believe you could set the log.flush.interval (http://incubator.apache.org/kafka/configuration.html) property to 0 on the server.  I think this will make Kafka fsync to disk after every message is received.  It's terrible for performance, but it would help the data verification tests.

**Comment by ppekrol** [comment]
1) I've checked the log.flush.interval, log.default.flush.scheduler.interval.ms and log.default.flush.interval.ms options and they seem to help a little bit, but still some messages are lost. I think there is not much we can do (at least from client side) to solve this situation. The client behaves as expected and it is processing all messages that are stored in kafka server.
